name: Changelog

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
      - name: Commit Changelog
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m 'chore: update changelog [skip ci]' || echo 'No changes to commit'
          git push
